COUNTRY = {
    'Angola': '安哥拉', 'Afghanistan': '阿富汗', 'Albania': '阿尔巴尼亚', 'Algeria': '阿尔及利亚', 'Andorra': '安道尔共和国',
    'Anguilla': '安圭拉岛', 'Antigua': 'and', 'Argentina': '阿根廷', 'Armenia': '亚美尼亚', 'Ascension': '阿森松',
    'Australia': '澳大利亚', 'Austria': '奥地利', 'Azerbaijan': '阿塞拜疆', 'Bahamas': '巴哈马', 'Bahrain': '巴林',
    'Bangladesh': '孟加拉国', 'Barbados': '巴巴多斯', 'Belarus': '白俄罗斯', 'Belgium': '比利时', 'Belize': '伯利兹',
    'Benin': '贝宁', 'Bermuda': 'Is.', 'Bolivia': '玻利维亚', 'Botswana': '博茨瓦纳', 'Brazil': '巴西', 'Brunei': '文莱',
    'Bulgaria': '保加利亚', 'Burkina-faso': '布基纳法索', 'Burma': '缅甸', 'Burundi': '布隆迪', 'Cameroon': '喀麦隆',
    'Canada': '加拿大', 'Cayman': 'Is.', 'Central': 'African', 'Chad': '乍得', 'Chile': '智利', 'China': '中国',
    'Colombia': '哥伦比亚', 'Congo': '刚果', 'Cook': 'Is.', 'Costa': 'Rica', 'Cuba': '古巴', 'Cyprus': '塞浦路斯',
    'Czech': 'Republic', 'Denmark': '丹麦', 'Djibouti': '吉布提', 'Dominica': 'Rep.', 'Ecuador': '厄瓜多尔',
    'Egypt': '埃及', 'EI': 'Salvador', 'Estonia': '爱沙尼亚', 'Ethiopia': '埃塞俄比亚', 'Fiji': '斐济', 'Finland': '芬兰',
    'France': '法国', 'French': 'Polynesia', 'Gabon': '加蓬', 'Gambia': '冈比亚', 'Georgia': '格鲁吉亚', 'Germany': '德国',
    'Ghana': '加纳', 'Gibraltar': '直布罗陀', 'Greece': '希腊', 'Grenada': '格林纳达', 'Guam': '关岛', 'Guatemala': '危地马拉',
    'Guinea': '几内亚', 'Guyana': '圭亚那', 'Haiti': '海地', 'Honduras': '洪都拉斯', 'Hongkong': '香港', 'Hungary': '匈牙利',
    'Iceland': '冰岛', 'India': '印度', 'Indonesia': '印度尼西亚', 'Iran': '伊朗', 'Iraq': '伊拉克', 'Ireland': '爱尔兰',
    'Israel': '以色列', 'Italy': '意大利', 'Ivory': 'Coast', 'Jamaica': '牙买加', 'Japan': '日本', 'Jordan': '约旦',
    'Kampuchea': '(Cambodia', 'Kazakstan': '哈萨克斯坦', 'Kenya': '肯尼亚', 'Korea': '韩国', 'Kuwait': '科威特',
    'Kyrgyzstan': '吉尔吉斯坦', 'Laos': '老挝', 'Latvia': '拉脱维亚', 'Lebanon': '黎巴嫩', 'Lesotho': '莱索托', 'Liberia': '利比里亚',
    'Libya': '利比亚', 'Liechtenstein': '列支敦士登', 'Lithuania': '立陶宛', 'Luxembourg': '卢森堡', 'Macao': '澳门',
    'Madagascar': '马达加斯加', 'Malawi': '马拉维', 'Malaysia': '马来西亚', 'Maldives': '马尔代夫', 'Mali': '马里', 'Malta': '马耳他',
    'Mariana': 'Is', 'Martinique': '马提尼克', 'Mauritius': '毛里求斯', 'Mexico': '墨西哥', 'Moldova,': 'Republic',
    'Monaco': '摩纳哥', 'Mongolia': '蒙古', 'Montserrat': 'Is', 'Morocco': '摩洛哥', 'Mozambique': '莫桑比克',
    'Namibia': '纳米比亚', 'Nauru': '瑙鲁', 'Nepal': '尼泊尔', 'Netheriands': 'Antilles', 'Netherlands': '荷兰',
    'New': 'Zealand', 'Nicaragua': '尼加拉瓜', 'Niger': '尼日尔', 'Nigeria': '尼日利亚', 'North': 'Korea', 'Norway': '挪威',
    'Oman': '阿曼', 'Pakistan': '巴基斯坦', 'Panama': '巴拿马', 'Papua': 'New', 'Paraguay': '巴拉圭', 'Peru': '秘鲁',
    'Philippines': '菲律宾', 'Poland': '波兰', 'Portugal': '葡萄牙', 'Puerto': 'Rico', 'Qatar': '卡塔尔', 'Reunion': '留尼旺',
    'Romania': '罗马尼亚', 'Russia': '俄罗斯', 'Saint': 'Vincent', 'Samoa': 'Western', 'San': 'Marino', 'Sao': 'Tome',
    'Saudi': 'Arabia', 'Senegal': '塞内加尔', 'Seychelles': '塞舌尔', 'Sierra': 'Leone', 'Singapore': '新加坡',
    'Slovakia': '斯洛伐克', 'Slovenia': '斯洛文尼亚', 'Solomon': 'Is', 'Somali': '索马里', 'South': 'Africa', 'Spain': '西班牙',
    'Sri': 'Lanka', 'St.Lucia': '圣卢西亚', 'St.Vincent': '圣文森特', 'Sudan': '苏丹', 'Suriname': '苏里南',
    'Swaziland': '斯威士兰', 'Sweden': '瑞典', 'Switzerland': '瑞士', 'Syria': '叙利亚', 'Taiwan': '台湾省',
    'Tajikstan': '塔吉克斯坦', 'Tanzania': '坦桑尼亚', 'Thailand': '泰国', 'Togo': '多哥', 'Tonga': '汤加', 'Trinidad': 'and',
    'Tunisia': '突尼斯', 'Turkey': '土耳其', 'Turkmenistan': '土库曼斯坦', 'Uganda': '乌干达', 'Ukraine': '乌克兰',
    'United': 'States', 'Uruguay': '乌拉圭', 'Uzbekistan': '乌兹别克斯坦', 'Venezuela': '委内瑞拉', 'Vietnam': '越南',
    'Yemen': '也门', 'Yugoslavia': '南斯拉夫', 'Zimbabwe': '津巴布韦', 'Zaire': '扎伊尔', 'Zambia': '赞比亚'
}
